### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxOCwibmFtZSI6Ik5BTkRJS0EiLCJlbWFpbCI6IjExMTIwMjMxNTE3OUBtaHMuZGludXMuYWMuaWQiLCJpYXQiOjE3ODA5ODg5NjcsImV4cCI6MTc4MTA3NTM2N30.Rthdzxijs9Oh7H7_Reb2JkhmSYyalSPecKbRQzlu8cg

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxOCwibmFtZSI6Ik5BTkRJS0EiLCJlbWFpbCI6IjExMTIwMjMxNTE3OUBtaHMuZGludXMuYWMuaWQiLCJpYXQiOjE3ODA5ODg5NjcsImV4cCI6MTc4MTA3NTM2N30.Rthdzxijs9Oh7H7_Reb2JkhmSYyalSPecKbRQzlu8cg
Content-Type: application/json

{
  "target_amount": 19000000,
  "present_amount": 2000700
}